import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[window]
decorations = "None"
dimensions = { columns = 191, lines = 43 }
padding = { x = 5, y = 5 }

[font]
size = 13.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Normal"

